# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Polish Reporting Platform -  indicators for the Sustainable Development Goals
description: Statistics Poland
baseurl: "http://sdg.gov.pl" # the subpath of your site, e.g. /blog
url: ""
data_dir: data

# Google Analytics
google_analytics: UA-139029935-1

#Github Repo
repo_name: sdg-indicators-pl
branch: gh-pages
org_name: Statistics Poland

# Build settings
markdown: kramdown

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  indicators:
    output: true
  goals:
    output: true
  translations:
    output: true
  metadane_globalne:
    output: true
  metadane_krajowe:
    output: true
